version: 0.1

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y openjdk-7-jdk
      - java -version
      - apt-get install -y maven
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - apt-get install -y maven
      - mvn clean install
      - echo Building the Docker image...
      - pwd          
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
  artifacts:
  files:
      - target/messageUtil-1.0.jar
        discard-paths:yes
